language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=540ad7483469a11da18f882673b4cb6a19199037ee808e02805977a5bad2af40
addons:
  chrome: stable
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
install:
- npm install
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm test
- npm run build
- npm run bundle
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
- npm run coverage
before_deploy:
- git checkout package.json
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
